### ISSUE TITLE
SyntaxError: Unexpected token ) running Gulp

### ISSUE THREAD

**Issue by mmacedoeu** [GoogleChrome/application-shell#58]
Got this running gulp:

```
macedo@macedo-Z97-D3H:~/w/application-shell$ gulp
/home/macedo/w/application-shell/gulp-tasks/service-worker.js:56
  .catch(() => {
          ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at requireDir (/home/macedo/w/application-shell/node_modules/require-dir/index.js:116:33)
    at Object.<anonymous> (/home/macedo/w/application-shell/gulpfile.js:23:23)
    at Module._compile (module.js:460:26)


```

**Comment by gauntface** [comment]
@mmacedoeu what version of node are you using?

`node --version`.

Me and Addy have likely been using 4.2.X

**Comment by mmacedoeu** [comment]
I installed in Ubuntu with apt-get install -y nodejs. Node version is
0.12.7. Bad Ubuntu !

Em sex, 18 de dez de 2015 12:18, Matthew Gaunt notifications@github.com
escreveu:

**Comment by mmacedoeu** [comment]
Works for v4.2.3
