### ISSUE TITLE
gulp fails 

### ISSUE THREAD

**Issue by slmyers** [GoogleChrome/application-shell#66]
```
steve@steve-FX6800-09h:~/javascript/service_worker/ver1/application-shell$ gulp
/home/steve/javascript/service_worker/ver1/application-shell/gulp-tasks/service-worker.js:57
  .catch(() => {
          ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at requireDir (/home/steve/javascript/service_worker/ver1/application-shell/node_modules/require-dir/index.js:116:33)
    at Object.<anonymous> (/home/steve/javascript/service_worker/ver1/application-shell/gulpfile.js:40:23)
    at Module._compile (module.js:460:26)
steve@steve-FX6800-09h:~/javascript/service_worker/ver1/application-shell$ gulp dev
/home/steve/javascript/service_worker/ver1/application-shell/gulp-tasks/service-worker.js:57
  .catch(() => {
          ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at requireDir (/home/steve/javascript/service_worker/ver1/application-shell/node_modules/require-dir/index.js:116:33)
    at Object.<anonymous> (/home/steve/javascript/service_worker/ver1/application-shell/gulpfile.js:40:23)
    at Module._compile (module.js:460:26)
```

I'm sure I'm making a mistake on my end, but I'm a `js` neophyte and the build process/ecosystem can be overwhelming. I thought you guys might appreciate being made aware of this error as I followed -- as far as I can tell -- the exact instruction from the Readme. That and node told me to tell you lel 

```
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/home/steve/.nvm/versions/node/v0.12.7/bin/node" "/home/steve/.nvm/versions/node/v0.12.7/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! app-shell@0.1.178 postinstall: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-shell@0.1.178 postinstall script 'gulp'.
npm ERR! This is most likely a problem with the app-shell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls app-shell
npm ERR! There is likely additional logging output above.
```

**Comment by gauntface** [comment]
Thanks for raising the issue @slmyers.

I'm suspecting this is something to do with your node version, what are you currently using?

At the moment I'm testing on 4.2.2 and in the package.json with have a [version of >=4.1.0](https://github.com/GoogleChrome/application-shell/blob/master/package.json#L7). 

Might be best to write something that checks and displays a meaningful error message if not a support version of node.

**Comment by slmyers** [comment]
Thanks for the help.
