### ISSUE TITLE
 error MSB6006: "CL.exe" exited with code -1073741515.

### ISSUE THREAD

**Issue by maygup** [GoogleChrome/application-shell#82]
While installing application-shell, I am getting following error:

```
C:\Users\cl\Documents\programs\reactjs\application-shell\application-shell\node_modules\sse4_crc32>if not defined npm_config_node_gyp (node "C:\Users\cl\Documents\softwares\node-v8.1.2-win-x64
\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\cl\Documents\programs\reactjs\applic
ation-shell\application-shell\node_modules\sse4_crc32\build\crc32c_sse42.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\cl\Documents\softwares\node-v8.1.2-win-x64\node_modules\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\cl\\Documents\\softwares\\node-v8.1.2-win-x64\\node.exe" "C:\\Users\\cl\\Documents\\softwares\\node-v8.1.2-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\
\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\cl\Documents\programs\reactjs\application-shell\application-shell\node_modules\sse4_crc32
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
```

Please help !

**Comment by maygup** [comment]
Seems to be an issue with node-sass. Will ask there. Thanks!
